import Head from "next/head"

export default function Home() {
   return (
      <div className="">
         <Head>
            <title>Portfolio - SAM M.</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <h2 className="text-xl">Welcome</h2>
      </div>
   )
}
